--- 
- name: Validate OCP Cluster against blueprint 
  hosts: localhost 
  vars:
    ocp_username: "{{ ansible_user }}" 
    ocp_password: "{{ ansible_password }}"
    ocp_api: "{{ ocp_api_host | default('localhost') }}"

  tasks:
        
    - block:
        - name: Authenticate to OCP and generate token
          redhat.openshift.openshift_auth:
            username: "{{ ocp_username }}"
            password: "{{ ocp_password }}"
            host: "{{ ocp_api }}"
            validate_certs: no 
          register: openshift_auth_results

        - name: Get worker node data 
          kubernetes.core.k8s_info:
            kind: Node
            label_selectors:
              - "node-role.kubernetes.io/worker"
            api_key: "{{ openshift_auth_results.openshift_auth.api_key }}"
            host: "{{ ocp_api }}"
          register: worker_node_list

        - name: Get control plane data 
          kubernetes.core.k8s_info:
            kind: Node
            label_selectors:
              - "node-role.kubernetes.io/control-plane"
            api_key: "{{ openshift_auth_results.openshift_auth.api_key }}"
            host: "{{ ocp_api }}"
          register: control_plane_list

        - name: Get cluster Network info 
          kubernetes.core.k8s_info:
            kind: Network
            api_version: config.openshift.io/v1
            api_key: "{{ openshift_auth_results.openshift_auth.api_key }}"
            host: "{{ ocp_api }}"
          register: cluster_network

        - name: Get ClusterVersion info
          kubernetes.core.k8s_info:
            kind: ClusterVersion
            api_key: "{{ openshift_auth_results.openshift_auth.api_key }}"
            host: "{{ ocp_api }}"
          register: cluster_version

        - name: Get StorageClass info
          kubernetes.core.k8s_info:
            kind: StorageClass
            api_key: "{{ openshift_auth_results.openshift_auth.api_key }}"
            host: "{{ ocp_api }}"
          register: storage_class

        - debug:
            msg: "{{ lookup('ansible.builtin.template', 'templates/cluster-report.yml.j2') }}"

        # - name: output as yaml
        #   ansible.builtin.template:
        #     src: templates/cluster-report.yml.j2
        #     dest: "./cluster-report.yml"

    #     # - name: Export the data to json file
    #     #   ansible.builtin.copy: content="{{ node_list | to_nice_json }}" dest="./nodes_output.json"

    #     - name: Output the report with the template
    #       ansible.builtin.template:
    #         src: templates/node-report.csv.j2
    #         dest: "./nodes_report.csv"



    #     - name: Cluster current version 
    #       debug: 
    #         msg: "Current OCP version: {{ cluster_version.resources[0].status.history[0].version }}" # in prod validate this to ensure state: Completed

    #     - name: Get StorageClass info
    #       kubernetes.core.k8s_info:
    #         kind: StorageClass
    #         api_key: "{{ openshift_auth_results.openshift_auth.api_key }}"
    #         host: "{{ ocp_api }}"
    #       register: storage_class

    #     - name: Available StorageClass definitions 
    #       debug: 
    #         msg: "{{ storage_class | json_query('resources[*].metadata.name') }}"

    #   always:
    #     - name: If login succeeded, try to log out (revoke access token)
    #       when: openshift_auth_results.openshift_auth.api_key is defined
    #       redhat.openshift.openshift_auth:
    #         state: absent
    #         api_key: "{{ openshift_auth_results.openshift_auth.api_key }}"
    #         host: "{{ ocp_api }}"
    #         validate_certs: no 